# Generated by Django 5.1.3 on 2025-03-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='id_proof',
            field=models.ImageField(blank=True, null=True, upload_to='id_proof'),
        ),
    ]
