# Generated by Django 5.1.3 on 2025-03-18 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='selected_date',
        ),
    ]
