# Generated by Django 5.1.3 on 2025-03-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_remove_booking_selected_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('booked', 'Booked'), ('ongoing', 'Ongoing'), ('complete', 'Complete'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
