# Generated by Django 5.1.3 on 2025-03-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('booked', 'Booked'), ('ongoing', 'Ongoing'), ('not arrived', 'Not Arrived'), ('completed', 'Completed'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
