# Generated by Django 5.1.3 on 2025-03-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_booking_platform_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='upi',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
