# Generated by Django 5.1.3 on 2025-03-28 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0011_card_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerSupport',
        ),
    ]
