# Generated by Django 5.1.3 on 2025-04-18 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0002_serviceprovider_id_proof'),
        ('user_app', '0012_delete_customersupport'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='service_app.serviceprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='user_app.user')),
            ],
        ),
    ]
